export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'


export const CREATE_TASK_BEGIN = 'CREATE_TASK_BEGIN'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'

export const GET_TASKS_BEGIN = 'GET_TASKS_BEGIN'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'

export const SET_DONE_TASK = 'SET_DONE_TASK'

export const DELETE_TASK_BEGIN = 'DELETE_TASK_BEGIN'

export const EDIT_TASK_BEGIN = 'EDIT_TASK_BEGIN'
export const EDIT_TASK_ERROR = 'EDIT_TASK_ERROR'